name: backend
on:
  pull_request:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup_backend
      - name: Build
        run: cargo build --verbose
        working-directory: backend
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Run test
        run: cargo test --verbose
        working-directory: backend
