name: frontend
on:
  pull_request:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup_frontend
      - name: Build
        run: elm-app build
        working-directory: frontend
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup_frontend
      - name: Run test
        run: elm-app test --verbose
        working-directory: frontend
